from pathlib import Path

path = Path('dataset/Foursquare/city_checkins')
path.mkdir(parents=True)
path = Path('dataset/Foursquare/dataset')
path.mkdir(parents=True)
path = Path('dataset/Foursquare/user_ratings')
path.mkdir(parents=True)

path = Path('dataset/Gowalla/city_checkins')
path.mkdir(parents=True)

path = Path('dataset/city_checkins')
path.mkdir(parents=True)
path = Path('dataset/user_ratings')
path.mkdir(parents=True)

path = Path('recomendation/train_test/Foursquare/JP_Tokyo')
path.mkdir(parents=True)
path = Path('recomendation/train_test/Foursquare/US_NewYork')
path.mkdir(parents=True)
path = Path('recomendation/train_test/Foursquare/US_SanFrancisco')
path.mkdir(parents=True)

path = Path('recomendation/train_test/Gowalla/JP_Tokyo')
path.mkdir(parents=True)
path = Path('recomendation/train_test/Gowalla/US_NewYork')
path.mkdir(parents=True)
path = Path('recomendation/train_test/Gowalla/US_SanFrancisco')
path.mkdir(parents=True)

path = Path('recomendation/users_recomendations/Foursquare/Hybrid')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Foursquare/Knn')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Foursquare/Popularity')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Foursquare/Random')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Foursquare/Skyline')
path.mkdir(parents=True)

path = Path('recomendation/users_recomendations/Gowalla/Hybrid')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Gowalla/Knn')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Gowalla/Popularity')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Gowalla/Random')
path.mkdir(parents=True)
path = Path('recomendation/users_recomendations/Gowalla/Skyline')
path.mkdir(parents=True)